version: 2
updates:
- package-ecosystem: cargo
  directories:
    - "/"
    - "/fuzz"
  schedule:
    interval: weekly
  allow:
    - dependency-type: all
  cooldown:
    default-days: 7
    semver-major-days: 14
    semver-minor-days: 7
    semver-patch-days: 3
  groups:
    rust-vmm:
      patterns:
        - "acpi_tables"
        - "kvm-bindings"
        - "kvm-ioctls"
        - "linux-loader"
        - "micro_http"
        - "mshv-bindings"
        - "mshv-ioctls"
        - "seccompiler"
        - "vfio-bindings"
        - "vfio-ioctls"
        - "vfio_user"
        - "vhost"
        - "vhost-user-backend"
        - "virtio-bindings"
        - "virtio-queue"
        - "vm-fdt"
        - "vm-memory"
        - "vmm-sys-util"
    non-rust-vmm:
      patterns:
        - "*"
      exclude-patterns:
        - "acpi_tables"
        - "kvm-bindings"
        - "kvm-ioctls"
        - "linux-loader"
        - "micro_http"
        - "mshv-bindings"
        - "mshv-ioctls"
        - "seccompiler"
        - "vfio-bindings"
        - "vfio-ioctls"
        - "vfio_user"
        - "vhost"
        - "vhost-user-backend"
        - "virtio-bindings"
        - "virtio-queue"
        - "vm-fdt"
        - "vm-memory"
        - "vmm-sys-util"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1